export type Difficulty = "beginner" | "intermediate" | "advanced";
export type Category = "bodyweight" | "stretch" | "fat-burning" | "gym";
export type MuscleGroup = "full-body" | "legs" | "core" | "chest" | "arms" | "back" | "glutes" | "cardio" | "shoulders" | "hips" | "neck" | "hamstrings" | "spine";

export interface Exercise {
  id: string;
  name: string;
  difficulty: Difficulty;
  category: Category;
  muscleGroups: MuscleGroup[];
  defaultDuration: number; // seconds
  demoImage: string; // AI-generated demo image URL
  description: string;
  instructions: string[];
  caloriesPerMinute: number;
}

export const EXERCISES: Exercise[] = [
  // ========== BEGINNER (5) ==========
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    difficulty: "beginner",
    category: "bodyweight",
    muscleGroups: ["full-body", "cardio"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/nxVKPVdWnRqMbWGM.png",
    description: "A classic full-body cardio exercise that raises your heart rate and warms up your muscles.",
    instructions: [
      "Stand upright with your legs together and arms at your sides.",
      "Jump and spread your legs shoulder-width apart while raising your arms overhead.",
      "Jump again to return to the starting position.",
      "Repeat at a steady pace.",
    ],
    caloriesPerMinute: 8,
  },
  {
    id: "bodyweight-squats",
    name: "Bodyweight Squats",
    difficulty: "beginner",
    category: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/rGNJstqgQcgELaCz.gif",
    description: "A fundamental lower body exercise that targets your quads, hamstrings, and glutes.",
    instructions: [
      "Stand with feet shoulder-width apart.",
      "Push your hips back and bend your knees as if sitting in a chair.",
      "Lower until your thighs are parallel to the floor.",
      "Drive through your heels to stand back up.",
    ],
    caloriesPerMinute: 6,
  },
  {
    id: "push-ups",
    name: "Push-Ups",
    difficulty: "beginner",
    category: "bodyweight",
    muscleGroups: ["chest", "arms", "core"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/jAenENpxehTqWmvS.png",
    description: "The classic upper body exercise that builds chest, shoulder, and tricep strength.",
    instructions: [
      "Start in a high plank position with hands slightly wider than shoulder-width.",
      "Keep your body in a straight line from head to heels.",
      "Lower your chest toward the floor by bending your elbows.",
      "Push back up to the starting position.",
    ],
    caloriesPerMinute: 7,
  },
  {
    id: "lunges",
    name: "Lunges",
    difficulty: "beginner",
    category: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/wlDbRJIaOsnepYNU.png",
    description: "A unilateral leg exercise that improves balance and lower body strength.",
    instructions: [
      "Stand tall with feet hip-width apart.",
      "Step forward with one leg and lower your hips.",
      "Both knees should bend to about 90 degrees.",
      "Push back to the starting position and alternate legs.",
    ],
    caloriesPerMinute: 6,
  },
  {
    id: "high-knees",
    name: "High Knees",
    difficulty: "beginner",
    category: "bodyweight",
    muscleGroups: ["cardio", "legs"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/vHJcRDPstAmcGatw.png",
    description: "A high-intensity cardio exercise that strengthens your legs and core.",
    instructions: [
      "Stand with your feet hip-width apart.",
      "Drive one knee up toward your chest.",
      "Quickly switch to the other knee.",
      "Pump your arms as you alternate knees at a running pace.",
    ],
    caloriesPerMinute: 9,
  },

  // ========== INTERMEDIATE (5) ==========
  {
    id: "burpees",
    name: "Burpees",
    difficulty: "intermediate",
    category: "bodyweight",
    muscleGroups: ["full-body", "cardio"],
    defaultDuration: 45,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/qpsCPSlFtKuEbzkp.gif",
    description: "A high-intensity full-body exercise that combines a squat, push-up, and jump.",
    instructions: [
      "Stand with feet shoulder-width apart.",
      "Drop into a squat and place your hands on the floor.",
      "Jump your feet back into a plank and perform a push-up.",
      "Jump your feet forward and explode upward into a jump.",
    ],
    caloriesPerMinute: 12,
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    difficulty: "intermediate",
    category: "bodyweight",
    muscleGroups: ["full-body", "cardio", "core"],
    defaultDuration: 45,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/DQXKfopkbFhbIQhD.gif",
    description: "A dynamic exercise that builds cardiovascular endurance and core strength.",
    instructions: [
      "Start in a high plank position.",
      "Drive one knee toward your chest.",
      "Quickly switch legs, bringing the other knee forward.",
      "Continue alternating at a fast pace.",
    ],
    caloriesPerMinute: 10,
  },
  {
    id: "plank-hold",
    name: "Plank Hold",
    difficulty: "intermediate",
    category: "bodyweight",
    muscleGroups: ["core", "full-body"],
    defaultDuration: 45,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/COAZYJBYifUyUJbK.png",
    description: "An isometric core exercise that strengthens your entire midsection.",
    instructions: [
      "Start in a forearm plank position with elbows under shoulders.",
      "Keep your body in a straight line from head to heels.",
      "Engage your core and avoid letting your hips sag or pike.",
      "Hold the position for the set duration.",
    ],
    caloriesPerMinute: 5,
  },
  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    difficulty: "intermediate",
    category: "bodyweight",
    muscleGroups: ["core"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/dfagGMUHWHIaqGti.png",
    description: "An effective core exercise that targets your obliques and rectus abdominis.",
    instructions: [
      "Lie on your back with hands behind your head.",
      "Lift your shoulders off the ground and bring one knee toward your chest.",
      "Rotate your torso to touch the opposite elbow to the knee.",
      "Alternate sides in a pedaling motion.",
    ],
    caloriesPerMinute: 7,
  },
  {
    id: "jump-squats",
    name: "Jump Squats",
    difficulty: "intermediate",
    category: "bodyweight",
    muscleGroups: ["legs", "cardio"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/BZWpgoPVQDGAudvC.gif",
    description: "An explosive plyometric exercise that builds lower body power.",
    instructions: [
      "Stand with feet shoulder-width apart.",
      "Lower into a squat position.",
      "Explode upward into a jump, extending your body fully.",
      "Land softly and immediately lower into the next squat.",
    ],
    caloriesPerMinute: 10,
  },

  // ========== ADVANCED (5) ==========
  {
    id: "pistol-squats",
    name: "Pistol Squats",
    difficulty: "advanced",
    category: "bodyweight",
    muscleGroups: ["legs"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/gPLcaTuweoGxLHyt.gif",
    description: "A challenging single-leg squat that requires strength, balance, and flexibility.",
    instructions: [
      "Stand on one leg with the other extended in front of you.",
      "Slowly lower your body on the standing leg.",
      "Go as low as you can while keeping balance.",
      "Push through your heel to stand back up.",
    ],
    caloriesPerMinute: 8,
  },
  {
    id: "handstand-push-ups",
    name: "Handstand Push-Ups",
    difficulty: "advanced",
    category: "bodyweight",
    muscleGroups: ["shoulders", "arms"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/ohfiostybSqFxwdX.png",
    description: "An advanced pressing exercise that builds incredible shoulder and arm strength.",
    instructions: [
      "Kick up into a handstand against a wall.",
      "Lower your head toward the floor by bending your elbows.",
      "Press back up to full arm extension.",
      "Maintain core tension throughout the movement.",
    ],
    caloriesPerMinute: 9,
  },
  {
    id: "muscle-ups",
    name: "Muscle-Ups",
    difficulty: "advanced",
    category: "bodyweight",
    muscleGroups: ["back", "arms", "chest"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/GyyRwFIYEEyciqPS.png",
    description: "A compound movement combining a pull-up and dip in one explosive motion.",
    instructions: [
      "Hang from a pull-up bar with an overhand grip.",
      "Pull yourself up explosively with a slight swing.",
      "Transition your chest over the bar.",
      "Press up to full arm extension above the bar.",
    ],
    caloriesPerMinute: 10,
  },
  {
    id: "planche-push-ups",
    name: "Planche Push-Ups",
    difficulty: "advanced",
    category: "bodyweight",
    muscleGroups: ["chest", "shoulders", "core"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/CBlXUMsjxNhjxWJg.gif",
    description: "An elite-level push-up variation with feet elevated for extreme upper body engagement.",
    instructions: [
      "Place your feet on an elevated surface (bench or box).",
      "Position hands on the floor, leaning forward significantly.",
      "Lower your chest toward the floor maintaining body tension.",
      "Press back up with control.",
    ],
    caloriesPerMinute: 9,
  },
  {
    id: "l-sit-hold",
    name: "L-Sit Hold",
    difficulty: "advanced",
    category: "bodyweight",
    muscleGroups: ["core", "arms"],
    defaultDuration: 20,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/efDhAfwLSBypMarY.png",
    description: "An isometric hold that demands exceptional core and hip flexor strength.",
    instructions: [
      "Sit on the floor with legs extended or use parallel bars.",
      "Place hands beside your hips and press down to lift your body.",
      "Raise your legs to form an L-shape with your torso.",
      "Hold the position with legs parallel to the floor.",
    ],
    caloriesPerMinute: 6,
  },

  // ========== STRETCH (5) ==========
  {
    id: "neck-stretch",
    name: "Neck Stretch",
    difficulty: "beginner",
    category: "stretch",
    muscleGroups: ["neck"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/ZrtzmolRWQEwbvsq.gif",
    description: "A gentle stretch to relieve neck tension and improve range of motion.",
    instructions: [
      "Sit or stand with a straight spine.",
      "Gently tilt your head toward one shoulder.",
      "Place your hand on the opposite side of your head for a gentle assist.",
      "Hold for 15 seconds, then switch sides.",
    ],
    caloriesPerMinute: 2,
  },
  {
    id: "hamstring-stretch",
    name: "Hamstring Stretch",
    difficulty: "beginner",
    category: "stretch",
    muscleGroups: ["hamstrings", "legs"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/MsLuyBQgdheBzkUt.png",
    description: "A seated stretch that improves hamstring flexibility and reduces lower back tension.",
    instructions: [
      "Sit on the floor with legs extended straight in front of you.",
      "Reach forward toward your toes with both hands.",
      "Keep your back as straight as possible.",
      "Hold the stretch and breathe deeply.",
    ],
    caloriesPerMinute: 2,
  },
  {
    id: "cat-cow-stretch",
    name: "Cat-Cow Stretch",
    difficulty: "beginner",
    category: "stretch",
    muscleGroups: ["spine", "core"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/xtlraUsRagCyjVoI.png",
    description: "A yoga-inspired spinal mobility exercise that warms up the back and core.",
    instructions: [
      "Start on hands and knees in a tabletop position.",
      "Inhale and arch your back, dropping your belly (Cow).",
      "Exhale and round your spine, tucking your chin (Cat).",
      "Flow between the two positions with your breath.",
    ],
    caloriesPerMinute: 3,
  },
  {
    id: "pigeon-pose",
    name: "Pigeon Pose",
    difficulty: "intermediate",
    category: "stretch",
    muscleGroups: ["hips", "glutes"],
    defaultDuration: 45,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/tbIfxrrWilSqsLiR.png",
    description: "A deep hip-opening stretch that targets the glutes and hip flexors.",
    instructions: [
      "From a tabletop position, bring one knee forward behind your wrist.",
      "Extend the other leg straight behind you.",
      "Lower your hips toward the floor.",
      "Hold and breathe, then switch sides.",
    ],
    caloriesPerMinute: 2,
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    difficulty: "intermediate",
    category: "stretch",
    muscleGroups: ["full-body", "hips", "spine"],
    defaultDuration: 45,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/nmKhhEbylnIKgCWE.png",
    description: "A dynamic full-body stretch that opens hips, thoracic spine, and hamstrings.",
    instructions: [
      "Step into a deep lunge with your right foot forward.",
      "Place your left hand on the floor inside your right foot.",
      "Rotate your torso and reach your right arm toward the ceiling.",
      "Hold briefly, return, and switch sides.",
    ],
    caloriesPerMinute: 3,
  },

  // ========== FAST FAT BURNING (3) ==========
  {
    id: "high-intensity-sprints",
    name: "High-Intensity Sprints",
    difficulty: "intermediate",
    category: "fat-burning",
    muscleGroups: ["cardio", "legs", "full-body"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/TlkHcKxOHiubLomW.png",
    description: "Maximum-effort sprinting intervals that torch calories and boost metabolism.",
    instructions: [
      "Stand in a ready position with feet hip-width apart.",
      "Sprint in place as fast as possible, driving knees high.",
      "Pump your arms explosively with each stride.",
      "Maintain maximum effort for the full interval.",
    ],
    caloriesPerMinute: 15,
  },
  {
    id: "star-jumps",
    name: "Star Jumps",
    difficulty: "intermediate",
    category: "fat-burning",
    muscleGroups: ["full-body", "cardio"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/ICZnNWiJpRAyJkMU.gif",
    description: "An explosive plyometric jump that engages your entire body for maximum calorie burn.",
    instructions: [
      "Start in a squat position with arms tucked in.",
      "Explode upward, spreading arms and legs into an X shape.",
      "Land softly back in the squat position.",
      "Immediately repeat for continuous movement.",
    ],
    caloriesPerMinute: 12,
  },
  {
    id: "speed-skaters",
    name: "Speed Skaters",
    difficulty: "intermediate",
    category: "fat-burning",
    muscleGroups: ["legs", "cardio", "glutes"],
    defaultDuration: 30,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/CmltLxkKyQvrdleE.png",
    description: "Lateral bounding exercise that improves agility and burns fat rapidly.",
    instructions: [
      "Stand on one leg with a slight bend in your knee.",
      "Leap laterally to the opposite side, landing on the other foot.",
      "Swing the trailing leg behind the landing leg.",
      "Continue alternating sides in a skating motion.",
    ],
    caloriesPerMinute: 11,
  },

  // ========== GYM (2) ==========
  {
    id: "barbell-deadlift",
    name: "Barbell Deadlift",
    difficulty: "advanced",
    category: "gym",
    muscleGroups: ["back", "legs", "glutes", "full-body"],
    defaultDuration: 60,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/FVToPuARgtRUpLnl.png",
    description: "The king of compound exercises — builds total body strength from the ground up.",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot.",
      "Hinge at the hips and grip the bar just outside your knees.",
      "Drive through your heels, keeping the bar close to your body.",
      "Stand tall at the top, then reverse the movement to lower.",
    ],
    caloriesPerMinute: 8,
  },
  {
    id: "bench-press",
    name: "Bench Press",
    difficulty: "advanced",
    category: "gym",
    muscleGroups: ["chest", "arms", "shoulders"],
    defaultDuration: 60,
    demoImage: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663279123655/rEoitFxHVHWHaEVM.png",
    description: "The classic chest-building exercise using a barbell on a flat bench.",
    instructions: [
      "Lie on a flat bench with eyes under the barbell.",
      "Grip the bar slightly wider than shoulder-width.",
      "Unrack and lower the bar to your mid-chest.",
      "Press the bar back up to full arm extension.",
    ],
    caloriesPerMinute: 7,
  },
];

export const CATEGORIES: { id: Category; label: string; icon: string }[] = [
  { id: "bodyweight", label: "Bodyweight", icon: "figure.walk" },
  { id: "stretch", label: "Stretch", icon: "figure.cooldown" },
  { id: "fat-burning", label: "Fat Burning", icon: "flame.fill" },
  { id: "gym", label: "Gym", icon: "dumbbell.fill" },
];

export const DIFFICULTY_COLORS: Record<Difficulty, { bg: string; text: string }> = {
  beginner: { bg: "#34C759", text: "#FFFFFF" },
  intermediate: { bg: "#FF9500", text: "#FFFFFF" },
  advanced: { bg: "#FF3B30", text: "#FFFFFF" },
};

export const CATEGORY_COLORS: Record<Category, { bg: string; text: string }> = {
  bodyweight: { bg: "#007AFF", text: "#FFFFFF" },
  stretch: { bg: "#AF52DE", text: "#FFFFFF" },
  "fat-burning": { bg: "#FF6B35", text: "#FFFFFF" },
  gym: { bg: "#5856D6", text: "#FFFFFF" },
};

export const DEFAULT_REST_TIME = 15; // seconds
